### ISSUE TITLE
Installing Petio throws an error message

### ISSUE THREAD

**Issue by townsmcp** [doob187/Traefikv2#23]
**Describe the bug**
I have gone to install Petio from the apps install and I get an error message:

![image](https://user-images.githubusercontent.com/14061617/114861365-13314600-9de5-11eb-87dd-f91c01a0ec10.png)

I have performed a git pull on the apps directory but still get this error message show

**Comment by doob187** [comment]
Please pull again
I made some adjustments

**Comment by townsmcp** [comment]
@doob187 just ran a 'git pull' from /opt/apps and then 'bash install.sh'. Went through the install, request, petio and still getting the same message as before

**Comment by doob187** [comment]
Please again
And report

**Comment by townsmcp** [comment]
@doob187 thanks - it has now installed :)
