### ISSUE TITLE
Error message when deploying Plex

### ISSUE THREAD

**Issue by townsmcp** [doob187/Traefikv2#24]
**Describe the bug**
I have perofmed a git pull on Traefik (and run a new deployment - everything is working as expected), and also a git pull on apps. When I try to install Plex, I claim the server as prompted and an error message shows on screen then the screen goes back to allowin an app to be installed:
![image](https://user-images.githubusercontent.com/14061617/115006249-91065780-9ea0-11eb-9808-d82bdb89168a.png)

I see that there are no files/directories under the plex directory:
![image](https://user-images.githubusercontent.com/14061617/115021560-06c7ee80-9eb4-11eb-85a0-02676afa6384.png)

**Comment by doob187** [comment]
Please pull and report

**Comment by townsmcp** [comment]
Did a git pull on apps but getting the following error message:
![image](https://user-images.githubusercontent.com/14061617/115050189-697cb280-9ed3-11eb-909d-87b4dea6a2b1.png)

**Comment by doob187** [comment]
Repull

**Comment by townsmcp** [comment]
No errors this time. No confirmation the app has deployed and no link to the external URL.
Also the docker contain doesnt start. When i try starting it I get the following error message:
![image](https://user-images.githubusercontent.com/14061617/115056739-1b6bad00-9edb-11eb-9179-e629ff2be80c.png)
In the container log it just shows:
```
No logs available
```

**Comment by doob187** [comment]
```sh
ls -la /dev/dri
```

**Comment by townsmcp** [comment]
DOH! Of course, I forgot to passthrough hardware transcoding to this container (did it on a seperate Plex container a week ago). Followed this link:
https://forums.plex.tv/t/pms-installation-guide-when-using-a-proxmox-5-1-lxc-container/219728
All now working :)

**Comment by doob187** [comment]
@all-contributors please add @townsmcp for test and bugs
